// <auto-generated />
using System;
using GitInsight.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitInsight.Entities.Migrations
{
    [DbContext(typeof(GitInsightContext))]
    [Migration("20221104153808_secondCreate")]
    partial class secondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitInsight.Entities.AnalyzedRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RepositoryIdString")
                        .HasColumnType("text");

                    b.Property<DateTime>("State")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AnalyzedRepos");
                });

            modelBuilder.Entity("GitInsight.Entities.DataCommit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalyzedRepoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StringId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedRepoId");

                    b.ToTable("DataCommits");
                });

            modelBuilder.Entity("GitInsight.Entities.DataCommit", b =>
                {
                    b.HasOne("GitInsight.Entities.AnalyzedRepo", null)
                        .WithMany("CommitsInRepo")
                        .HasForeignKey("AnalyzedRepoId");
                });

            modelBuilder.Entity("GitInsight.Entities.AnalyzedRepo", b =>
                {
                    b.Navigation("CommitsInRepo");
                });
#pragma warning restore 612, 618
        }
    }
}
